services:
    _defaults:
        autowire: true      # автоматически инжектирует зависимости
        autoconfigure: true # автоматически регистрирует сервисы

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Явная регистрация обработчиков успеха и неудачи
    App\Security\CustomAuthenticationSuccessHandler:
        arguments:
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
            $tokenStorage: '@security.token_storage'

    App\Security\CustomAuthenticationFailureHandler: ~
