nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['%env(FRONTEND_URL)%']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['POST', 'GET', 'PUT', 'DELETE', 'OPTIONS']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/api/': ~